### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by laactech** [revsys/django-test-plus#113]
Thanks for this package. It has made testing django a lot easier.

- **OS version and name**: Ubuntu 18.04
- **python version**: 3.8
- **django version**: 3.0
- **django-test-plus version**: 1.3.1

When I attempt to run my test suite, I receive this error

```python
ImportError: cannot import name 'curry' from 'django.utils.functional'
```
I believe that Django 3.0 removes this due to the drop in Python 2 support.

https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

To achieve Django 3.0 support, I believe this will have to be removed.

**Comment by jefftriplett** [comment]
@laactech this looked fixed in #110 which is in the master branch currently. I just updated tests in #114 which should be good-to-go once CI catches up. 

@frankwiles would you mind rolling a release once tests pass?

**Comment by frankwiles** [comment]
Thanks everyone, just released 1.4.0 with Django 3.0 support.

**Comment by laactech** [comment]
Thanks for the help and quick response.

**Comment by frankyjquintero** [comment]
When will the new version compatible with django 3 be available?

**Comment by frankwiles** [comment]
Version 1.4.0 was released right after this was closed.  I forgot to tag it.  Version 1.4.0 should work for you.
