### ISSUE TITLE
Something broke?

### ISSUE THREAD

**Issue by simkimsia** [revsys/django-test-plus#133]
![image](https://user-images.githubusercontent.com/245021/88886122-65890180-d26c-11ea-9085-077118f8f27b.png)

I am having this issue when I build. Did something break recently? Because my last build at 3 days ago was fine using the same version of django-test-plus

3 days ago

![image](https://user-images.githubusercontent.com/245021/88886684-9c134c00-d26d-11ea-996f-8a1bfb065f9f.png)

**Comment by simkimsia** [comment]
I need to push something to merge with main branch. But I am stuck because this fails. Can advise?

**Comment by frankwiles** [comment]
@simkimsia looks like this might have been a networking issue between you and PyPI.  I can install that version just fine. 

![Screen Shot 2020-07-30 at 8 45 25 AM](https://user-images.githubusercontent.com/144159/88930375-09f54e80-d241-11ea-937d-cf0dc9b1daa1.png)

**Comment by simkimsia** [comment]
Ok thank you  @frankwiles It's actually on circleci. I will raise this issue to them in that case.

**Comment by adamzap** [comment]
@simkimsia Thanks for reporting this. I'm getting it on a different CI service. Would you mind updating this issue once you resolve it somehow or hear from CircleCI?

**Comment by simkimsia** [comment]
Hi @adamzap 

They told me to install wheel

I'm not sure why I have to do this now when I never have to before

![image](https://user-images.githubusercontent.com/245021/88996824-d4c02d80-d320-11ea-8a6d-15aa8739bb72.png)

What about u? What did ur CI say?

**Comment by simkimsia** [comment]
Hi @adamzap 

I have decided to take the circleci support advice and add `&& pip install wheel` to the config for circleci.

It appears that I have got past that error. Not sure what's the equivalent of that for your CI. Hope this helps. My tests are being runned and yet to complete, but I have confidence 🤞  everything should be fine now.

THank you

**Comment by adamzap** [comment]
I'm glad that worked for you! I was about to try installing `wheel` manually, but when I ran CI again this morning it was working again. Weird! Thanks for the help!
