### ISSUE TITLE
self.get/post method do not explain well how to use follow=True 

### ISSUE THREAD

**Issue by pydanny** [revsys/django-test-plus#15]
Makes testing forms kind of a pain. Would you consider adding it as a stand-alone parameter to those methods (I can do the PR if you want)?

**Comment by frankwiles** [comment]
Yeah that's a good idea happy to get a PR!

**Comment by pydanny** [comment]
Actually, what about including it as a direct argument of self.get/self.post itself?

**Comment by frankwiles** [comment]
Yeah that's what I was thinking.
