### ISSUE TITLE
Is Django 4 supported?

### ISSUE THREAD

**Issue by kevinrenskers** [revsys/django-test-plus#185]
It's not mentioned in the readme. Is the readme out of date, or is Django 4 not supported?

**Comment by frankwiles** [comment]
The README is just out of date.  It should work fine with Django 4

**Comment by jefftriplett** [comment]
We have used `django-test-plus` on several Django 4.x projects and it works. I updated the README, workflows, and trove classifiers tonight which should help clear the way to a new release. All of this is in our main branch.

**Comment by kevinrenskers** [comment]
Thanks!

**Comment by jefftriplett** [comment]
@frankwiles would you mind publishing a release to get the Django 4.x trove classifiers updated?

**Comment by frankwiles** [comment]
Done, 2.2.1 just released.
