### ISSUE TITLE
Documentation about CBVTestCase

### ISSUE THREAD

**Issue by jambonrose** [revsys/django-test-plus#19]
Hi,
In `README.rst`, the documentation imports `CBVTestCase` with:

    from test_plus import CBVTestCase

This leads to an `ImportError` in my case.

There appear to be two ways to fix this:

1. change the documentation to read: `from test_plus.test import CBVTestCase`
2. import the `CBVTestCase` class to the package `__init__.py` file

I favor the second more than the first. I'm happy to submit a PR.

**Comment by frankwiles** [comment]
Thanks for reporting that!
