### ISSUE TITLE
Python and Django support? 

### ISSUE THREAD

**Issue by jefftriplett** [revsys/django-test-plus#196]
What versions of Python and Django do we want to target? 

I know REVSYS uses `django-test-plus` for porting older projects, but that shouldn't be too hard to juggle.

**Comment by jefftriplett** [comment]
Following back up. I think it's safe to target Django 3.2 and like-minded Python versions with respect to porting clients.

**Comment by frankwiles** [comment]
Yeah I think it's fine to target 3.2 + going forward and just use an older version of django-test-plus on older projects since nothing about newer versions is security related or so amazing we'd miss it terribly.
