### ISSUE TITLE
Behaviour of TestCase.post is not as expected

### ISSUE THREAD

**Issue by goodtune** [revsys/django-test-plus#29]
I have a test using the `post` method which is failing under a use case I would expect to work.

```
def test_some_view(self):
    data = {}
    self.post('named:view', data)
    self.response_302()
```
The above test case is failing, because the response code is 404 not 302.

However if I rework the test case as below, it now works with the desired side effects.
```
def test_some_view(self):
    data = {}
    url = self.reverse('named:view')
    res = self.client.post(url, data)
    self.assertEqual(res.status_code, 302)
```

Is there anything obvious that is wrong in my usage of the `post` method, or is this a bug?

**Comment by goodtune** [comment]
I'd add, looking at [the source](https://github.com/revsys/django-test-plus/blob/master/test_plus/test.py#L123-L137) there isn't much that I think can go wrong, so I'm struggling to explain it.

**Comment by frankwiles** [comment]
Hmmm yeah this pattern is used all the time so if it was breaking in a general way I'd be running into it daily myself.  I'm gonna guess perhaps there was a typo of 'named:view' that you fixed when you reworked it maybe? 

If you can create a reproducible case please reopen this. Thanks!
