### ISSUE TITLE
assertNumQueriesLessThan -> assertNumQueriesLessThanOrEqualTo

### ISSUE THREAD

**Issue by ftobia** [revsys/django-test-plus#30]
The behavior of "assertNumQueriesLessThan" is actually less than or equal to.

https://github.com/revsys/django-test-plus/blob/a09b7233272ff0753ccb2bc838584910a5a0aeee/test_plus/test.py#L42

I suggest one of:
 - change the name to match the behavior
 - change the behavior to match the name
 - include both functions and make the behavior correct for each

**Comment by frankwiles** [comment]
Oooh good catch thanks for reporting it!
