### ISSUE TITLE
pytest support

### ISSUE THREAD

**Issue by ftobia** [revsys/django-test-plus#31]
I use pytest for testing, so I don't use Django's TestCase directly. pytest-django is a package that provides fixtures that wrap Django's TestCase.

Would you be amenable to providing pytest fixtures for your helpers, like pytest-django does? If so I'd be happy to put together a pull request for you to look over.

**Comment by renatooliveira** [comment]
:+1:

**Comment by frankwiles** [comment]
I suppose I'm not sure what you really asking here.  I use django-test-plus with pytest on 90% of my projects.  But honestly I only use pytest-django to provide --reuse-db and --nomigrations. 

Can you be a bit more specific about what you're wanting to achieve?

**Comment by ftobia** [comment]
Sure.

pytest lets you write tests using both `unittest.TestCase` subclasses and arbitrary functions / methods. django-test-plus provides a TestCase subclass with a bunch of helper methods. Those are inaccessible if I want to have a test that isn't a subclass of TestCase, e.g. a standalone test function:

    def test_foo():
        assert 1 + 1 = 2
        # I want to use assertNumQueriesLessThan in here. How can I?

A way that pytest-django provides some functionality is through pytest fixtures. See: https://pytest-django.readthedocs.org/en/latest/helpers.html#fixtures

    # From the link above:
    def test_with_client(client):
        response = client.get('/')
        assert response.content == 'Foobar'

So I was thinking something like:

    def test_foo(plus):
        with plus.assertNumQueriesLessThan(10):
            some_cool_function()

I added something like this in my own codebase (just an example, probably not the best approach to implement it generally):

    @pytest.fixture
    def helper():
        return Helper()


    class Helper(object):
        """
        Helper for writing tests.
        """

        def __init__(self):
            self.tc = self.create_test_plus_testcase()

        def create_test_plus_testcase(self):
            from test_plus.test import TestCase

            class _ConcreteTestCase(TestCase):
                def runTest(self):
                    pass

            return _ConcreteTestCase()

        def assert_num_queries(self, num_queries):
            return self.tc.assertNumQueries(num_queries)

Thoughts? Questions? Concerns?

**Comment by hetsch** [comment]
@ftobia Thank's for your solution, this works pretty well for me. Based on your code, I have hacked the following together:

    class Helper(object):

        def __init__(self):
            self.tc = self.create_test_plus_testcase()

        def create_test_plus_testcase(self):
            from test_plus.test import TestCase

            class _ConcreteTestCase(TestCase):
                pass

            return _ConcreteTestCase()

        def __getattr__(self, name):
            # Called if there are no attributes in the instance that match the name.
            # Delegate to TestCase.
            return getattr(self.tc, name)

**Comment by mimischi** [comment]
@frankwiles Any plans to include this or something similar in the `pytest-django` package?

**Comment by frankwiles** [comment]
I definitely would like to do it, it's just a matter of finding the time.

**Comment by frankwiles** [comment]
Forgot to close this, it got added in the last release.  You just need to have `tp` as an argument to your functions and it gives you a compatible TestPlus class.  

https://github.com/revsys/django-test-plus#pytest-usage
