### ISSUE TITLE
How to use token authentication while testing REST API

### ISSUE THREAD

**Issue by Darwesh27** [revsys/django-test-plus#43]
I am using django rest framework's token authentication in my django project and I need to unit test my ModelViewSets but the default `login` method of the TestCase class in not doing the job. I'm using drf's TokenAuthentication.

```
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    )
}
```

**Comment by frankwiles** [comment]
Hi @Darwesh27, 

Yeah the `login` method only works with Django Session auth, you should just `force_authenticate()` in your tests using DRF's method for that.  Docs for that are here http://www.django-rest-framework.org/api-guide/testing/#forcing-authentication

**Comment by eracle** [comment]
I've solved using the credentials methods, here's the [gist](https://gist.github.com/eracle/7da3ce964a86729ce044361c44c400e1).

**Comment by sahir** [comment]
@eracle gist (Error 404)

**Comment by captbilard** [comment]
@eracle link gives error 404. Kindly help with the right link

**Comment by eracle** [comment]
sorry guys, it seems desappeared from my gist list

**Comment by Olfredos6** [comment]
> sorry guys, it seems desappeared from my gist list

Submit  a new one

**Comment by eracle** [comment]
Unfortunately, I don't have that code anymore.
