### ISSUE TITLE
Add a form error helper

### ISSUE THREAD

**Issue by epicserve** [revsys/django-test-plus#46]
When debugging tests I added the following to my own personal base TestCase class, which has been really handy. I could do a PR if this seems like something that would be good to add.

```
def print_form_errors(self, resp_or_form=None):

    if resp_or_form is None:
        resp_or_form = self.last_response

    if not isinstance(resp_or_form, (forms.Form, forms.ModelForm)):
        form = resp_or_form.context['form']
    else:
        form = resp_or_form
    print(form.errors.as_text())
```

**Comment by frankwiles** [comment]
This looks like it could be useful, but maybe I need more coffee I'm not sure what this does for the user. Can you explain a bit more?

**Comment by epicserve** [comment]
@frankwiles, if you have a test that isn't working because of some form errors, you just run the method to see what the errors are.

```
self.post('my-url', data={})
self.print_form_errors()
```

**Comment by frankwiles** [comment]
I like it, feel free to submit a PR!
