### ISSUE TITLE
Sending JSON String in post request

### ISSUE THREAD

**Issue by PabloVallejo** [revsys/django-test-plus#47]
I'd love to know how to send a raw JSON string in the request body. 
Currently I'm passing the string directly to `data`, but it specs a dictionary instead.

```python
response = self.post(
    'my-url',
    data=json_string,
)
```

Any thoughts on this?

**Comment by frankwiles** [comment]
You would need to drop back down to using the Django TestClient directly and do something like this: http://stackoverflow.com/a/18176166/12568
