### ISSUE TITLE
get method not supporting kwargs

### ISSUE THREAD

**Issue by ensignavenger** [revsys/django-test-plus#5]
I am trying to rewrite the following to use test case plus:

self.client.get(reverse('search'),{'query': 1})

From the readme, I gather that I should be able to do:

self.get('search', query=1)

But I am getting:
django.core.urlresolvers.NoReverseMatch: Reverse for 'search' with arguments '()' and keyword arguments '{'query': 1}' not found. 1 pattern(s) tried: ['search']

So I tried:
response = self.get('search', extra={'query': 1})
But that doesn't work, either.  The source translates that to:
response = self.client.get(reverse('search'), query=1)
Which passes my query as a Header!

It looks like to satisfy my use case, we need to add another 'special' key in addition to extra, that simply passes the dict to client.get() as an argument, rather than converting it into a kwarg.

Any thoughts?

**Comment by frankwiles** [comment]
Can you show me the pattern in your urls.py you're trying to match against.  I'm confused as to what you're trying to pass along to it!

**Comment by ensignavenger** [comment]
the urls.py entry is:
url(r'^search', views.search, name='search'),

The actual URL would look like:
mydomain.tld/search?query=1

**Comment by frankwiles** [comment]
As it turns out Django's TestClient.get() handles this with the first kwargs argument named 'data'.  So I've just adjusted our get() to pull it out and pass it along for you.  Will be in 1.0.5 which I'm releasing in just a few minutes.
