### ISSUE TITLE
'TestCase' object has no attribute 'assertResponseContains'

### ISSUE THREAD

**Issue by ndanielsen** [revsys/django-test-plus#51]
Great testing util that you're maintaining here. I'm getting this error when running a basic test. 

AttributeError: 'IssueTestCase' object has no attribute 'assertResponseContains'

**Comment by frankwiles** [comment]
Thanks! Sounds like you aren't importing and inheriting from our TestCase.  You need to have something like:

```
from test_plus import TestCase

class IssueTestCase(TestCase):
    # Your code here....
```
