### ISSUE TITLE
Can't make email user through `make_user`

### ISSUE THREAD

**Issue by Leop0ld** [revsys/django-test-plus#55]
https://github.com/revsys/django-test-plus/blob/master/test_plus/test.py#L264

Can't make email user through make_user

I am using `email` field instead of `username` field in `User` class.
So, I registered `email` to USERNAME_FIELD.
And I customized `UserManager` class by fitting in `User` model.

My conclusion is `make_user` method needs options that help not using username and also using another field name.

P.S. Maybe I think that can solve this problem using `USERNAME_FIELD`.
Or change name `make_user` method to `_make_user` method and make new `make_user` method can receive option not using `username` field.

This is entirely my suggestion, not the compulsion.

**Comment by jefftriplett** [comment]
We solved this recently by using `USERNAME_FIELD` as you described here to match my `email` field. Let us know if this is still an issue for you; otherwise, we'll close it out.

**Comment by Leop0ld** [comment]
@jefftriplett It was solved a few month ago. Thanks :)
