### ISSUE TITLE
Make the self.post() and self.get() work with urls

### ISSUE THREAD

**Issue by epicserve** [revsys/django-test-plus#7]
I have situations where I've already reversed a named url and it doesn't make sense to do the work twice. For example, it would be nice if I could do this:

```python
url = self.reverse('things:thing_update', pk=thing.pk)
self.get(url)
self.post(url, data={})
```

You could make this work by adding some logic that says if the ``url_name`` startswith '/' or 'http' then just use it as a url and don't reverse it.

**Comment by epicserve** [comment]
PS, as a work around I know I can use ``self.client.get()`` or ``self.client.post()``. However, that's extra typing and I want to be lazy. :)

**Comment by epicserve** [comment]
Just a thought, but what about using ``django.core.urlresolvers.is_valid_path`` instead of a try and except. That seems a little more clean to me.

**Comment by frankwiles** [comment]
Yeah that's an option, but this assumes that 99% of the use cases will be named URLs and not full valid URLs, so it's a VERY VERY small touch faster.  And I think just about as clean as the is_valid_path which just hides the try/except for you in another function call.

**Comment by epicserve** [comment]
Works for me.
