### ISSUE TITLE
Add helper for adding needed permissions

### ISSUE THREAD

**Issue by epicserve** [revsys/django-test-plus#8]
I have stuff like this in my tests:

```python
user = self.make_user('testuser')
user.user_permissions.add(*list(Permission.objects.filter(codename__endswith='user')))
```

If would be nice if I could so something like this:

```python
user = self.make_user('testuser', model_perms=[User, FooModel])
```

This would just add the permissions available for the models you pass with the model_perms argument.

**Comment by epicserve** [comment]
@frankwiles if this sounds like a good idea, I would be happy to submit a PR.

**Comment by frankwiles** [comment]
I don't think it's a bad idea, but I'm not sure model_perms=[ <List of Models> ] is generic enough for everyone.  Normally I would handle this with Factory Boy I think.

**Comment by epicserve** [comment]
@frankwiles I think you close this since you accepted my PR. :)

**Comment by frankwiles** [comment]
heh yep just forgot to close it.
